name: website

on:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install Depedencies
        run: npm install
      -
        name: Build App
        run: npm run build
